/*
 * Copyright 2026 Onur Kat
 * SPDX-License-Identifier: Apache-2.0
 */
package com.onurkat.reclazz.plugin.hybris

import com.intellij.openapi.diagnostic.Logger
import com.intellij.openapi.project.Project
import com.onurkat.reclazz.plugin.agent.AgentJarLocator
import com.onurkat.reclazz.plugin.settings.ReclazzSettings
import java.nio.file.Files
import java.nio.file.Path

/**
 * Puts the Reclazz agent into a SAP Commerce server's startup options.
 *
 * ## Why properties and not wrapper.conf
 *
 * Hybris servers start through the Tanuki wrapper, so the agent has to
 * reach `tomcat/conf/wrapper.conf`. Writing there directly is the obvious
 * move and it is wrong: that file is GENERATED. Its whole
 * `wrapper.java.additional.N` block comes from properties, and any ant
 * run that regenerates the config (`ant clean all`, `ant server`, ...)
 * rewrites it from the template. An agent line added by hand survives
 * until the developer's next clean build, then vanishes with no error and
 * no log line — hot-reload simply stops working and nothing says why.
 *
 * The platform documents the supported seam in its own
 * project.properties:
 *
 *     # Java runtime options for the hybris Server in normal operation
 *     # Note that these settings are appended to the tomcat.generaloptions
 *     tomcat.javaoptions=
 *     tomcat.debugjavaoptions=
 *
 * Both are folded into the generated wrapper configs — `javaoptions` into
 * wrapper.conf, `debugjavaoptions` into wrapper-debug.conf, which is what
 * `hybrisserver.sh debug` reads. Writing there means the agent is put
 * back by the very regeneration that used to remove it.
 *
 * ## Where it writes
 *
 * Into the last properties layer Hybris reads (see
 * [HybrisPropertyFiles]), as its own `99-reclazz.properties` when an
 * optional config directory exists. Existing values are read from the
 * layers below and preserved: `tomcat.debugjavaoptions` normally carries
 * the JDWP flags, and dropping those would break debugging.
 */
object HybrisAgentInstaller {

    private val log = Logger.getInstance(HybrisAgentInstaller::class.java)

    private const val MARKER_BEGIN = "# >>> reclazz (auto-generated by Reclazz plugin — do not edit between markers)"
    private const val MARKER_END = "# <<< reclazz"

    private const val JAVA_OPTIONS = "tomcat.javaoptions"
    private const val DEBUG_JAVA_OPTIONS = "tomcat.debugjavaoptions"

    /** Generated files earlier versions used to edit; cleaned up on install. */
    private val LEGACY_WRAPPER_CONFS = listOf("wrapper.conf", "wrapper-debug.conf")

    sealed class Result {
        data class Success(val message: String) : Result()
        data class Error(val message: String) : Result()
    }

    private fun configDir(project: Project): Path? =
        HybrisProjectDetector.findHybrisHome(project)?.resolve("config")
            ?.takeIf { Files.isDirectory(it) }

    private fun platformHome(project: Project): Path? =
        HybrisProjectDetector.findHybrisHome(project)
            ?.resolve("bin")?.resolve("platform")
            ?.takeIf { Files.isDirectory(it) }

    /** The properties file Reclazz writes into, when the project has one. */
    fun targetFile(project: Project): Path? =
        configDir(project)?.let { HybrisPropertyFiles.targetFile(it) }

    fun isInstalled(project: Project): Boolean {
        val target = targetFile(project) ?: return false
        return try {
            Files.isRegularFile(target) && Files.readString(target).contains(MARKER_BEGIN)
        } catch (e: Exception) {
            false
        }
    }

    fun install(project: Project): Result {
        val hybrisHome = HybrisProjectDetector.findHybrisHome(project)
            ?: return Result.Error("Hybris home not found. This action only works for SAP Commerce projects.")
        val configDir = configDir(project)
            ?: return Result.Error("config directory not found under $hybrisHome.")
        val platformHome = platformHome(project)
            ?: return Result.Error("bin/platform not found under $hybrisHome.")

        // The stable copy, not the bundled one: the path written here ends
        // up in properties the server starts from, and the IDE's plugin
        // directory is named after the IDE version. See stableAgentJar.
        val pluginAgentJar = AgentJarLocator.stableAgentJar()
            ?: return Result.Error("Bundled agent jar not found. Reinstall the Reclazz plugin.")

        // Legacy cleanup: ≤1.0.22 copied the agent jar into the project.
        try {
            Files.deleteIfExists(hybrisHome.resolve(".reclazz").resolve("agent.jar"))
        } catch (e: Exception) {
            log.warn("Could not remove legacy agent copy: ${e.message}")
        }
        removeLegacyWrapperBlocks(platformHome)

        val settings = ReclazzSettings.getInstance(project).state
        val agentArg = agentArgument(
            "${pluginAgentJar.toPath().toAbsolutePath()}=" +
                    AgentJarLocator.buildAgentArgs(project, settings)
        )

        // Read what the user already has, from every layer except ours, so
        // appending never erases their JDWP flags or custom options.
        val existingJavaOptions = HybrisPropertyFiles
            .effectiveValue(platformHome, configDir, JAVA_OPTIONS)
        val existingDebugOptions = HybrisPropertyFiles
            .effectiveValue(platformHome, configDir, DEBUG_JAVA_OPTIONS)

        val target = HybrisPropertyFiles.targetFile(configDir)
        val block = buildBlock(agentArg, existingJavaOptions, existingDebugOptions)

        return try {
            writeBlock(target, block)

            // Prove, rather than assume, that the only thing this install
            // changed is the agent. Everything Reclazz writes overrides a
            // property somebody else may rely on, so a silent mistake here
            // would change how their server starts.
            verifyOnlyAgentAdded(platformHome, configDir, agentArg)?.let { problem ->
                return Result.Error(
                    "Install aborted and rolled back: $problem This is a bug — " +
                    "please report it at https://github.com/onurkat/reclazz/issues."
                ).also { rollback(target) }
            }

            val ownFile = !HybrisPropertyFiles.writesIntoUserFile(configDir)
            // The next step is NOT just a restart. wrapper.conf is generated
            // from these properties at ant time, so a server started against
            // the existing wrapper.conf would not see the change and the user
            // would conclude the install did nothing.
            val nextStep = "Run `ant server` (or any build that regenerates the config), " +
                    "then restart your SAP Commerce server."
            val note = if (ownFile) {
                // Our own file: uninstall deletes it and nothing of theirs
                // was touched.
                "Reclazz created ${target.fileName} in your optional config directory. $nextStep"
            } else {
                // Their file. Say so plainly, and flag the part that bites
                // teams: the line contains a path that only exists on this
                // machine, so committing it breaks everyone else.
                "Reclazz added a block to ${target.fileName} (backed up as " +
                "${target.fileName}.reclazz-bak). It contains a path specific to this " +
                "machine, so keep it out of version control. $nextStep"
            }
            Result.Success(note)
        } catch (e: Exception) {
            Result.Error("Failed to write ${target.fileName}: ${e.message}")
        }
    }

    fun uninstall(project: Project): Result {
        val target = targetFile(project)
            ?: return Result.Error("SAP Commerce config directory not found.")
        if (!Files.isRegularFile(target)) {
            return Result.Error("Reclazz block not found: ${target.fileName} does not exist.")
        }

        return try {
            val content = Files.readString(target)
            if (!content.contains(MARKER_BEGIN)) {
                return Result.Error("Reclazz block not found in ${target.fileName}.")
            }
            val cleaned = removeMarkerBlock(content)
            // A file that exists only for our block is removed outright
            // rather than left behind as an empty stub.
            if (target.fileName.toString() == HybrisPropertyFiles.RECLAZZ_PROPERTIES &&
                cleaned.isBlank()
            ) {
                Files.deleteIfExists(target)
            } else {
                Files.writeString(target, cleaned)
            }
            platformHome(project)?.let { removeLegacyWrapperBlocks(it) }
            Result.Success("Removed Reclazz from ${target.fileName}. Restart the server to apply.")
        } catch (e: Exception) {
            Result.Error("Failed to write ${target.fileName}: ${e.message}")
        }
    }

    /** Prefix recording what a property held before Reclazz touched it. */
    private const val BASE_MARKER = "# reclazz-base:"

    private fun buildBlock(
        agentArg: String,
        existingJavaOptions: String,
        existingDebugOptions: String
    ): String = buildString {
        append(MARKER_BEGIN).append('\n')
        append("# Reclazz appends its agent through the platform's documented\n")
        append("# append properties. wrapper.conf is generated from these, so the\n")
        append("# agent survives `ant clean all` instead of being wiped by it.\n")
        append("#\n")
        append("# These lines OVERRIDE the same properties set elsewhere, because\n")
        append("# this file is read last. The reclazz-base lines below record what\n")
        append("# each property held before Reclazz touched it: everything after\n")
        append("# that value is the agent and nothing else. Reclazz compares them\n")
        append("# on startup, so if you change your own options it will notice its\n")
        append("# copy is stale and offer to re-sync instead of quietly winning.\n")
        append("$BASE_MARKER$JAVA_OPTIONS=$existingJavaOptions\n")
        append("$BASE_MARKER$DEBUG_JAVA_OPTIONS=$existingDebugOptions\n")
        append("$JAVA_OPTIONS=${joinOptions(existingJavaOptions, agentArg)}\n")
        append("$DEBUG_JAVA_OPTIONS=${joinOptions(existingDebugOptions, agentArg)}\n")
        append(MARKER_END).append('\n')
    }

    /**
     * Check that each managed property now reads as "what it was, plus the
     * agent" and nothing else.
     *
     * @return a description of the first discrepancy, or null when clean.
     */
    internal fun verifyOnlyAgentAdded(
        platformHome: Path,
        configDir: Path,
        agentArg: String
    ): String? {
        val target = HybrisPropertyFiles.targetFile(configDir)
        for (key in listOf(JAVA_OPTIONS, DEBUG_JAVA_OPTIONS)) {
            val base = recordedBase(target, key) ?: return "$key lost its recorded base value."
            val effective = HybrisPropertyFiles.effectiveValue(platformHome, configDir, key)
            // effectiveValue skips our file, so it reports the user's value.
            if (effective.trim() != base.trim()) {
                return "$key changed underneath the install (expected '${base.trim()}', found '${effective.trim()}')."
            }
            val written = HybrisPropertyFiles.readProperty(target, key)
                ?: return "$key was not written to ${target.fileName}."
            if (written.trim() != joinOptions(base, agentArg).trim()) {
                return "$key would have been changed beyond adding the agent."
            }
        }
        return null
    }

    /** Undo a write that failed verification, leaving the project as found. */
    private fun rollback(target: Path) {
        try {
            if (!Files.isRegularFile(target)) return
            val cleaned = removeMarkerBlock(Files.readString(target))
            if (target.fileName.toString() == HybrisPropertyFiles.RECLAZZ_PROPERTIES && cleaned.isBlank()) {
                Files.deleteIfExists(target)
            } else {
                Files.writeString(target, cleaned)
            }
        } catch (e: Exception) {
            log.warn("Rollback of ${target.fileName} failed: ${e.message}")
        }
    }

    /**
     * The agent jar the installed configuration points at, when that file
     * no longer exists.
     *
     * A `-javaagent` naming a missing jar does not merely disable
     * hot-reload: the JVM refuses to start. Whatever leaves a stale path
     * behind — an older install pointing into an IDE version that has since
     * been replaced, a manually edited file — the next server start fails
     * with a message about a zip file, so this is worth catching while the
     * developer is still in the IDE.
     */
    fun missingAgentJar(project: Project): Path? {
        val target = targetFile(project) ?: return null
        if (!isInstalled(project)) return null

        val value = HybrisPropertyFiles.readProperty(target, JAVA_OPTIONS) ?: return null
        val path = parseAgentJarPath(value) ?: return null

        val jar = Path.of(path)
        return if (Files.isRegularFile(jar)) null else jar
    }

    /**
     * Pull the jar path out of a `-javaagent:` option.
     *
     * Written two ways depending on the path: bare, or quoted when it
     * contains a space — which is the macOS default, since the plugin lives
     * under "Application Support". A single regex over non-whitespace would
     * quietly fail on exactly that case and the staleness check would never
     * fire where it is needed most.
     */
    internal fun parseAgentJarPath(value: String): String? {
        val marker = value.indexOf("-javaagent:")
        if (marker == -1) return null
        val rest = value.substring(marker + "-javaagent:".length)

        val pathAndArgs = if (rest.startsWith("\"")) {
            rest.substring(1).substringBefore('"')
        } else {
            rest.substringBefore(' ')
        }

        val jarEnd = pathAndArgs.indexOf(".jar")
        return if (jarEnd == -1) null else pathAndArgs.substring(0, jarEnd + ".jar".length)
    }

    /** Base value Reclazz recorded for [key], or null when not installed. */
    private fun recordedBase(target: Path, key: String): String? {
        if (!Files.isRegularFile(target)) return null
        return try {
            Files.readAllLines(target)
                .firstOrNull { it.startsWith("$BASE_MARKER$key=") }
                ?.substringAfter("$BASE_MARKER$key=")
        } catch (e: Exception) {
            null
        }
    }

    /**
     * Whether the user's own options have moved on since Reclazz copied
     * them, which means Reclazz's file is now silently overriding a value
     * the user has since changed.
     *
     * Returns the properties that drifted; empty when in sync or when
     * Reclazz is not installed.
     */
    fun driftedProperties(project: Project): List<String> {
        val configDir = configDir(project) ?: return emptyList()
        val platformHome = platformHome(project) ?: return emptyList()
        val target = HybrisPropertyFiles.targetFile(configDir)
        if (!isInstalled(project)) return emptyList()

        return listOf(JAVA_OPTIONS, DEBUG_JAVA_OPTIONS).filter { key ->
            val recorded = recordedBase(target, key) ?: return@filter false
            val current = HybrisPropertyFiles.effectiveValue(platformHome, configDir, key)
            recorded.trim() != current.trim()
        }
    }

    private fun joinOptions(existing: String, agentArg: String): String =
        if (existing.isBlank()) agentArg else "${existing.trim()} $agentArg"

    /**
     * Build the `-javaagent:` option, quoting the value when it contains a
     * space.
     *
     * These properties are split into individual `wrapper.java.additional.N`
     * lines on whitespace. An unquoted path with a space is therefore not
     * "one option with a space" but two broken fragments, and the platform
     * drops the whole thing: the generated wrapper.conf simply has no agent
     * line and the server starts silently without hot-reload.
     *
     * This is the normal case, not an edge case: on macOS the plugin lives
     * under `~/Library/Application Support/JetBrains/...`. Quoting is the
     * platform's own convention here, and it emits the matching
     * `.stripquotes=TRUE` line so the JVM receives the value unquoted.
     */
    internal fun agentArgument(pathAndArgs: String): String =
        if (pathAndArgs.contains(' ')) "-javaagent:\"$pathAndArgs\"" else "-javaagent:$pathAndArgs"

    private fun writeBlock(target: Path, block: String) {
        Files.createDirectories(target.parent)

        val existing = if (Files.isRegularFile(target)) Files.readString(target) else ""
        val cleaned = removeMarkerBlock(existing)

        // Back up a file we did not create, once.
        if (existing.isNotEmpty() && target.fileName.toString() != HybrisPropertyFiles.RECLAZZ_PROPERTIES) {
            val backup = target.resolveSibling("${target.fileName}.reclazz-bak")
            if (!Files.exists(backup)) {
                try {
                    Files.copy(target, backup)
                } catch (e: Exception) {
                    log.warn("Failed to back up ${target.fileName}: ${e.message}")
                }
            }
        }

        val content = if (cleaned.isBlank()) block else cleaned.trimEnd('\n', '\r') + "\n\n" + block
        Files.writeString(target, content)
    }

    /**
     * Strip blocks earlier versions wrote into the generated wrapper
     * configs. Harmless if already gone: ant deletes them on its own,
     * which is the bug this replaces.
     */
    private fun removeLegacyWrapperBlocks(platformHome: Path) {
        val confDir = platformHome.resolve("tomcat").resolve("conf")
        for (name in LEGACY_WRAPPER_CONFS) {
            val file = confDir.resolve(name)
            try {
                if (!Files.isRegularFile(file)) continue
                val content = Files.readString(file)
                if (!content.contains(MARKER_BEGIN)) continue
                Files.writeString(file, removeMarkerBlock(content))
                log.info("Removed legacy Reclazz block from $name")
            } catch (e: Exception) {
                log.warn("Could not clean legacy block in $name: ${e.message}")
            }
        }
    }

    private fun removeMarkerBlock(content: String): String {
        val begin = content.indexOf(MARKER_BEGIN)
        if (begin == -1) return content
        val endMarker = content.indexOf(MARKER_END, begin)
        if (endMarker == -1) return content
        val endOfLine = content.indexOf('\n', endMarker)
        val absoluteEnd = if (endOfLine == -1) content.length else endOfLine + 1
        val remainder = content.removeRange(begin, absoluteEnd).trimEnd('\n', '\r')
        return if (remainder.isBlank()) "" else remainder + "\n"
    }
}
