/*
 * Copyright 2026 Onur Kat
 * SPDX-License-Identifier: Apache-2.0
 */
package com.onurkat.reclazz.plugin.hybris

import org.junit.jupiter.api.Test
import kotlin.test.assertEquals
import kotlin.test.assertFalse

/**
 * Installing writes into a file the server starts from, which means removing
 * has to put that file back exactly as it was.
 *
 * The stakes are not symmetrical with installing. A bad install is noticed at
 * once, because the server is right there in front of the developer who asked
 * for it. A bad uninstall is noticed weeks later by somebody else, when a
 * server will not boot and nothing on screen connects that to a plugin that is
 * no longer installed. Someone evaluating this tool has to be able to walk away
 * from it cleanly, or trying it is not a small decision.
 */
class AgentUninstallTest {

    private val block = """
        # >>> reclazz (auto-generated by Reclazz plugin — do not edit between markers)
        # reclazz-base:tomcat.javaoptions=-Xmx4G
        tomcat.javaoptions=-Xmx4G -javaagent:/home/u/.reclazz/agent/reclazz-agent.jar=hybrisHome=/srv
        # <<< reclazz
    """.trimIndent() + "\n"

    @Test
    fun `removing the block restores the file exactly`() {
        val before = "db.url=jdbc:mysql://localhost/hybris\ntomcat.javaoptions=-Xmx4G\n"

        val after = HybrisAgentInstaller.removeMarkerBlock(before + block)

        assertEquals(before, after, "everything outside the markers is the user's and must survive untouched")
    }

    /**
     * A left-behind agent line is the failure that matters: a -javaagent
     * pointing at a jar that is gone does not degrade to "no hot reload", it
     * stops the JVM from starting at all.
     */
    @Test
    fun `no agent argument survives the removal`() {
        val cleaned = HybrisAgentInstaller.removeMarkerBlock(
            "some.property=x\n" + block + "other.property=y\n"
        )

        assertFalse(cleaned.contains("javaagent"), "an orphan -javaagent line stops the server from booting")
        assertFalse(cleaned.contains("reclazz"), "no trace of ours may be left in a file the server reads")
        assertEquals("some.property=x\nother.property=y\n", cleaned)
    }

    @Test
    fun `removing twice is not worse than removing once`() {
        val once = HybrisAgentInstaller.removeMarkerBlock("keep=1\n" + block)
        val twice = HybrisAgentInstaller.removeMarkerBlock(once)

        assertEquals(once, twice, "a repeated uninstall must be a no-op, not a second bite out of the file")
    }

    @Test
    fun `a file that was never installed into is returned untouched`() {
        val theirs = "tomcat.javaoptions=-Xmx8G\n# a comment they wrote\n"

        assertEquals(theirs, HybrisAgentInstaller.removeMarkerBlock(theirs))
    }
}
