/*
 * Copyright 2026 Onur Kat
 * SPDX-License-Identifier: Apache-2.0
 */
package com.onurkat.reclazz.plugin.hybris

import org.junit.jupiter.api.Test
import org.junit.jupiter.api.io.TempDir
import java.nio.file.Files
import java.nio.file.Path
import kotlin.test.assertEquals
import kotlin.test.assertNull
import kotlin.test.assertTrue

/**
 * Reclazz's properties file is read last, so every property it writes
 * overrides whatever the project set. That is a lot of leverage over how
 * somebody's server starts, and the promise that comes with it is narrow:
 * the agent is added and nothing else is touched.
 *
 * These tests hold that promise to the character.
 */
class AgentInstallScopeTest {

    @TempDir
    lateinit var tmp: Path

    private lateinit var configDir: Path
    private lateinit var platformHome: Path

    private val agentArg = "-javaagent:/plugins/reclazz/agent.jar=hybrisHome=/srv"

    private fun setUp(userDebugOptions: String = "-Xdebug -Xrunjdwp:transport=dt_socket") {
        configDir = Files.createDirectories(tmp.resolve("hybris/config"))
        platformHome = Files.createDirectories(tmp.resolve("hybris/bin/platform"))
        Files.writeString(platformHome.resolve("project.properties"),
            "tomcat.javaoptions=\ntomcat.debugjavaoptions=\n")
        Files.writeString(configDir.resolve("local.properties"),
            "hybris.optional.config.dir=\${HYBRIS_CONFIG_DIR}/dev/props\n")
        val props = Files.createDirectories(configDir.resolve("dev/props"))
        Files.writeString(props.resolve("10-local.properties"),
            "tomcat.debugjavaoptions=$userDebugOptions\n" +
            "some.unrelated.property=untouched\n")
    }

    /** Writes the block the installer would write, without needing a Project. */
    private fun writeInstallBlock(): Path {
        val target = HybrisPropertyFiles.targetFile(configDir)
        val baseJava = HybrisPropertyFiles.effectiveValue(platformHome, configDir, "tomcat.javaoptions")
        val baseDebug = HybrisPropertyFiles.effectiveValue(platformHome, configDir, "tomcat.debugjavaoptions")
        Files.writeString(target, """
            # >>> reclazz (auto-generated by Reclazz plugin — do not edit between markers)
            # reclazz-base:tomcat.javaoptions=$baseJava
            # reclazz-base:tomcat.debugjavaoptions=$baseDebug
            tomcat.javaoptions=${listOf(baseJava, agentArg).filter { it.isNotBlank() }.joinToString(" ")}
            tomcat.debugjavaoptions=${listOf(baseDebug, agentArg).filter { it.isNotBlank() }.joinToString(" ")}
            # <<< reclazz
        """.trimIndent() + "\n")
        return target
    }

    @Test
    fun `installing adds the agent and changes nothing else`() {
        setUp()
        val target = writeInstallBlock()

        assertNull(
            HybrisAgentInstaller.verifyOnlyAgentAdded(platformHome, configDir, agentArg),
            "verification must accept an install that only adds the agent"
        )

        // And spelled out: the written value is the user's value plus ours.
        val written = HybrisPropertyFiles.readProperty(target, "tomcat.debugjavaoptions")
        assertEquals("-Xdebug -Xrunjdwp:transport=dt_socket $agentArg", written)
    }

    @Test
    fun `the user's JDWP flags survive the install verbatim`() {
        setUp(userDebugOptions = "-Xdebug -Xrunjdwp:transport=dt_socket,server=y,address=8000,suspend=n")
        val target = writeInstallBlock()

        val written = HybrisPropertyFiles.readProperty(target, "tomcat.debugjavaoptions")!!

        assertTrue(
            written.startsWith("-Xdebug -Xrunjdwp:transport=dt_socket,server=y,address=8000,suspend=n "),
            "debugging must keep working: $written"
        )
        assertEquals(1, Regex("javaagent").findAll(written).count(),
            "the agent must appear exactly once")
    }

    @Test
    fun `verification rejects a value changed beyond adding the agent`() {
        setUp()
        val target = writeInstallBlock()

        // Simulate a bug that rewrote the user's options while installing.
        val corrupted = Files.readString(target)
            .replace("tomcat.debugjavaoptions=-Xdebug -Xrunjdwp:transport=dt_socket $agentArg",
                     "tomcat.debugjavaoptions=$agentArg")
        Files.writeString(target, corrupted)

        val problem = HybrisAgentInstaller.verifyOnlyAgentAdded(platformHome, configDir, agentArg)

        assertTrue(problem != null && problem.contains("tomcat.debugjavaoptions"),
            "dropping the user's options must be caught, got: $problem")
    }

    @Test
    fun `properties Reclazz does not manage are never written`() {
        setUp()
        val target = writeInstallBlock()

        val body = Files.readString(target)

        assertTrue(!body.contains("some.unrelated.property"),
            "Reclazz must not copy properties it does not manage")
        val assignments = body.lines()
            .filter { it.contains("=") && !it.trimStart().startsWith("#") }
            .map { it.substringBefore("=") }
        assertEquals(
            listOf("tomcat.javaoptions", "tomcat.debugjavaoptions"),
            assignments,
            "only the two documented append properties may be set"
        )
    }

    @Test
    fun `the configured agent path is extracted from the written value`() {
        // The startup check reads this back to see whether the jar still
        // exists. A path with spaces is quoted, so the pattern has to cope
        // with both forms or the check would silently never fire.
        setUp()
        val quoted = "-javaagent:\"/Users/me/Library/Application Support/x/agent.jar=hybrisHome=/srv\""
        val plain = "-javaagent:/opt/reclazz/agent.jar=hybrisHome=/srv"

        assertEquals(
            "/opt/reclazz/agent.jar",
            HybrisAgentInstaller.parseAgentJarPath(plain)
        )
        assertEquals(
            "/Users/me/Library/Application Support/x/agent.jar",
            HybrisAgentInstaller.parseAgentJarPath(quoted),
            "the macOS case, where the path contains a space, must resolve"
        )
        assertNull(
            HybrisAgentInstaller.parseAgentJarPath("-Xmx8G -Xdebug"),
            "a value without an agent has no path to report"
        )
    }

    @Test
    fun `a later change to the user's own options is detected as drift`() {
        setUp(userDebugOptions = "-Xdebug -original")
        writeInstallBlock()

        // The developer edits their own file afterwards. Reclazz's copy now
        // silently overrides it, which is exactly what must not pass unnoticed.
        Files.writeString(configDir.resolve("dev/props/10-local.properties"),
            "tomcat.debugjavaoptions=-Xdebug -original -Xmx8G\n")

        val recordedBase = Files.readAllLines(HybrisPropertyFiles.targetFile(configDir))
            .first { it.startsWith("# reclazz-base:tomcat.debugjavaoptions=") }
            .substringAfter("=")
        val current = HybrisPropertyFiles
            .effectiveValue(platformHome, configDir, "tomcat.debugjavaoptions")

        assertTrue(recordedBase.trim() != current.trim(),
            "the drift check compares these two values and must see a difference")
    }
}
